version: '3.5'
volumes:
  data:
  logs:
services:
  db:
    build: ./pg
    env_file:
      - .env
    restart: always

    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
  auth:
    build: ./auth
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "3001:3001"
    volumes:
      - ./auth/logs:/logs
    environment:
      - TOKEN_KEY=${TOKEN_KEY}
      - KAFKA_USER=${KAFKA_USER}
      - KAFKA_PASSWORD=${KAFKA_PASSWORD}
      - INIT=${INIT}
  todo:
    build: ./todo
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "3002:3002"
    volumes:
      - ./todo/logs:/logs
    environment:
      - TOKEN_KEY=${TOKEN_KEY}
      - KAFKA_USER=${KAFKA_USER}
      - KAFKA_PASSWORD=${KAFKA_PASSWORD}
      - INIT=${INIT}
  todo_karafka:
    build: ./todo/lib/karafka
    env_file:
      - .env
    depends_on:
      - db
    environment:
      - KAFKA_USER=${KAFKA_USER}
      - KAFKA_PASSWORD=${KAFKA_PASSWORD}
  accounting:
    build: ./accounting
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "3003:3003"
    volumes:
      - ./todo/logs:/logs
    environment:
      - TOKEN_KEY=${TOKEN_KEY}
      - KAFKA_USER=${KAFKA_USER}
      - KAFKA_PASSWORD=${KAFKA_PASSWORD}
      - INIT=${INIT}
  accounting_karafka:
    build: ./accounting/lib/karafka
    env_file:
      - .env
    depends_on:
      - db
    environment:
      - KAFKA_USER=${KAFKA_USER}
      - KAFKA_PASSWORD=${KAFKA_PASSWORD}